import { ReactNode, VFC } from "react";
import { Header } from "../Header/Header";
import { Footer } from "../Footer/Footer";
import Head from "next/head";

type Props = {
  children: ReactNode;
};

export const Layout: VFC<Props> = (props) => {
  const { children } = props;
  return (
    <div className="flex justify-center px-2 items-center flex-col min-h-screen h-screen text-gray-600 text-sm ">
      <Head>
        <title>kurihara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/144x144-removebg-preview.png" />
      </Head>
      <Header />
      <main className="flex flex-1 justify-center items-center flex-col w-screen">
        {children}
      </main>
      <Footer />
    </div>
  );
};
