import { ReactNode, VFC } from "react";
import { Header } from "../Header/Header";
import { Footer } from "../Footer/Footer";
import Head from "next/head";

type Props = {
  children: ReactNode;
};

export const Layout: VFC<Props> = (props) => {
  const { children } = props;
  return (
    <div>
      <Head>
        <title>kurihara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
};
