import Head from "next/head";

import { Footer } from "../../components/Footer/Footer";
import { Blogs } from "../../components/Blogs/Blogs";
import { Header } from "../../components/Header/Header";

export default function Blog() {
  return (
    <div className="min-h-screen px-2 flex flex-col justify-center items-center h-screen">
      <Head>
        <title>kurihara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Blogs page="blog" />
      <Footer />
    </div>
  );
}
